#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = 'Synthetic Ocean AI - Team'
__email__ = 'syntheticoceanai@gmail.com'
__version__ = '{1}.{0}.{1}'
__initial_data__ = '2022/06/01'
__last_update__ = '2025/12/07'
__credits__ = ['Synthetic Ocean AI']

# MIT License
#
# Copyright (c) 2025 Synthetic Ocean AI
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

try:
    import sys
    import numpy
    from typing import Optional, List, Dict
    import torch

    from Engine.Architectures.Adversarial.Torch.VanillaGeneratorTorch import VanillaGeneratorTorch
    from Engine.Architectures.Adversarial.Torch.VanillaDiscriminatorTorch import VanillaDiscriminatorTorch

except ImportError as error:
    print(error)
    sys.exit(-1)

DEFAULT_ADVERSARIAL_LATENT_DIMENSION = 128
DEFAULT_ADVERSARIAL_INTERMEDIARY_ACTIVATION = "leaky_relu"
DEFAULT_ADVERSARIAL_LAST_ACTIVATION_LAYER = "sigmoid"
DEFAULT_ADVERSARIAL_DROPOUT_DECAY_RATE_G = 0.2
DEFAULT_ADVERSARIAL_DROPOUT_DECAY_RATE_D = 0.4
DEFAULT_ADVERSARIAL_INITIALIZER_MEAN = 0.0
DEFAULT_ADVERSARIAL_INITIALIZER_DEVIATION = 0.5
DEFAULT_ADVERSARIAL_DENSE_LAYERS_SETTINGS_G = [128]
DEFAULT_ADVERSARIAL_DENSE_LAYERS_SETTINGS_D = [128]


class AdversarialModelTorch:
    """
    AdversarialModelTorch

    Combines a generator and a discriminator in a unified adversarial model for PyTorch.
    Uses composition instead of multiple inheritance to avoid MRO conflicts.

    This class allows for seamless integration of both models in a Generative Adversarial
    Network (GAN) framework, with methods for initializing, configuring, and interacting
    with the generator and discriminator networks.

    Attributes:
        @latent_dimension (int):
            Dimensionality of the latent space used by the generator.
        @output_shape (int):
            Shape of the output generated by the generator and evaluated by the discriminator.
        @activation_function (str):
            Activation function applied to intermediate layers.
        @initializer_mean (float):
            Mean of the normal distribution used for weight initialization.
        @initializer_deviation (float):
            Standard deviation of the normal distribution used for weight initialization.
        @dropout_decay_rate_g (float):
            Dropout decay rate applied to the generator layers.
        @dropout_decay_rate_d (float):
            Dropout decay rate applied to the discriminator layers.
        @last_layer_activation (str):
            Activation function used for the last layer of both generator and discriminator.
        @dense_layer_sizes_g (List[int]):
            List of integers specifying the number of units per dense layer in the generator.
        @dense_layer_sizes_d (List[int]):
            List of integers specifying the number of units per dense layer in the discriminator.
        @dataset_type (torch.dtype):
            Data type used for input data (default: torch.float32).
        @number_samples_per_class (Optional[Dict]):
            Optional dictionary containing the number of samples per class, if applicable.

    Raises:
        ValueError:
            Raised if invalid arguments are provided, such as:
            - Non-positive `latent_dimension`
            - Dropout rates outside the range [0, 1]
            - Empty or invalid `dense_layer_sizes_g` or `dense_layer_sizes_d`
            - Missing required key "number_classes" in `number_samples_per_class`, if provided

    Example:
        >>> model = AdversarialModelTorch(
        ...     latent_dimension=100,
        ...     output_shape=784,
        ...     activation_function='relu',
        ...     initializer_mean=0.0,
        ...     initializer_deviation=0.02,
        ...     dropout_decay_rate_g=0.3,
        ...     dropout_decay_rate_d=0.3,
        ...     last_layer_activation='sigmoid',
        ...     dense_layer_sizes_g=[512, 256],
        ...     dense_layer_sizes_d=[512, 256],
        ...     dataset_type=torch.float32,
        ...     number_samples_per_class={"number_classes": 10}
        ... )
        >>> generator = model.get_generator()
        >>> discriminator = model.get_discriminator()
    """

    def __init__(self,
                 latent_dimension: int = DEFAULT_ADVERSARIAL_LATENT_DIMENSION,
                 output_shape: int = 128,
                 activation_function: str = DEFAULT_ADVERSARIAL_INTERMEDIARY_ACTIVATION,
                 initializer_mean: float = DEFAULT_ADVERSARIAL_INITIALIZER_MEAN,
                 initializer_deviation: float = DEFAULT_ADVERSARIAL_INITIALIZER_DEVIATION,
                 dropout_decay_rate_g: float = DEFAULT_ADVERSARIAL_DROPOUT_DECAY_RATE_G,
                 dropout_decay_rate_d: float = DEFAULT_ADVERSARIAL_DROPOUT_DECAY_RATE_D,
                 last_layer_activation: str = DEFAULT_ADVERSARIAL_LAST_ACTIVATION_LAYER,
                 dense_layer_sizes_g: Optional[List[int]] = None,
                 dense_layer_sizes_d: Optional[List[int]] = None,
                 dataset_type: torch.dtype = torch.float32,
                 number_samples_per_class: Optional[Dict] = None):
        """
        Initializes the AdversarialModelTorch by creating separate generator and discriminator instances.

        Args:
            latent_dimension (int):
                Dimensionality of the latent space used by the generator.
            output_shape (int):
                Shape of the generated output.
            activation_function (str):
                Activation function applied to all hidden layers.
            initializer_mean (float):
                Mean of the normal distribution for weight initialization.
            initializer_deviation (float):
                Standard deviation of the normal distribution for weight initialization.
            dropout_decay_rate_g (float):
                Dropout decay rate applied to the generator layers.
            dropout_decay_rate_d (float):
                Dropout decay rate applied to the discriminator layers.
            last_layer_activation (str):
                Activation function for the last layer of both models.
            dense_layer_sizes_g (Optional[List[int]]):
                List of integers specifying the number of units per dense layer in the generator.
            dense_layer_sizes_d (Optional[List[int]]):
                List of integers specifying the number of units per dense layer in the discriminator.
            dataset_type (torch.dtype, optional):
                Data type of the input dataset (default: torch.float32).
            number_samples_per_class (Optional[Dict], optional):
                Optional dictionary containing metadata about the number of samples per class.
                If provided, it must include the key "number_classes".

        Raises:
            ValueError:
                If `latent_dimension` is non-positive.
                If `dropout_decay_rate_g` or `dropout_decay_rate_d` is not within [0, 1].
                If `dense_layer_sizes_g` or `dense_layer_sizes_d` is empty or invalid.
                If `number_samples_per_class` is provided but does not contain the key "number_classes".
        """

        if dense_layer_sizes_d is None:
            dense_layer_sizes_d = DEFAULT_ADVERSARIAL_DENSE_LAYERS_SETTINGS_D.copy()

        if dense_layer_sizes_g is None:
            dense_layer_sizes_g = DEFAULT_ADVERSARIAL_DENSE_LAYERS_SETTINGS_G.copy()

        # Create generator instance using composition
        self._generator_builder = VanillaGeneratorTorch(
            latent_dimension=latent_dimension,
            output_shape=output_shape,
            activation_function=activation_function,
            initializer_mean=initializer_mean,
            initializer_deviation=initializer_deviation,
            dropout_decay_rate_g=dropout_decay_rate_g,
            last_layer_activation=last_layer_activation,
            dense_layer_sizes_g=dense_layer_sizes_g,
            dataset_type=dataset_type,
            number_samples_per_class=number_samples_per_class
        )

        # Create discriminator instance using composition
        self._discriminator_builder = VanillaDiscriminatorTorch(
            latent_dimension=latent_dimension,
            output_shape=output_shape,
            activation_function=activation_function,
            initializer_mean=initializer_mean,
            initializer_deviation=initializer_deviation,
            dropout_decay_rate_d=dropout_decay_rate_d,
            last_layer_activation=last_layer_activation,
            dense_layer_sizes_d=dense_layer_sizes_d,
            dataset_type=dataset_type,
            number_samples_per_class=number_samples_per_class
        )

    def get_generator(self):
        """
        Build and return the generator model.

        Returns:
            ConditionalGenerator: The generator model.
        """
        return self._generator_builder.get_generator()

    def get_discriminator(self):
        """
        Build and return the discriminator model.

        Returns:
            ConditionalDiscriminator: The discriminator model.
        """
        return self._discriminator_builder.get_discriminator()

    def get_dense_generator_model(self) -> Optional[torch.nn.Module]:
        """
        Returns the generator's dense model.

        Returns:
            Optional[torch.nn.Module]: The dense model of the generator, or None if not built.
        """
        return self._generator_builder.get_dense_generator_model()

    def get_dense_discriminator_model(self) -> Optional[torch.nn.Module]:
        """
        Returns the discriminator's dense model.

        Returns:
            Optional[torch.nn.Module]: The dense model of the discriminator, or None if not built.
        """
        return self._discriminator_builder.get_dense_discriminator_model()

    def set_latent_dimension(self, latent_dimension: int) -> None:
        """
        Sets the latent dimension for both the generator and discriminator.

        Args:
            latent_dimension (int): New latent dimension value.

        Raises:
            ValueError: If latent_dimension is not a positive integer.
        """
        if not isinstance(latent_dimension, int) or latent_dimension <= 0:
            raise ValueError("latent_dimension must be a positive integer.")

        self._generator_builder._generator_latent_dimension = latent_dimension
        self._discriminator_builder._discriminator_latent_dimension = latent_dimension

    def set_output_shape(self, output_shape: int) -> None:
        """
        Sets the output shape for both the generator and discriminator.

        Args:
            output_shape (int): New output shape value.

        Raises:
            ValueError: If output_shape is not a positive integer.
        """
        if not isinstance(output_shape, int) or output_shape <= 0:
            raise ValueError("output_shape must be a positive integer.")

        self._generator_builder._generator_output_shape = output_shape
        self._discriminator_builder._discriminator_output_shape = output_shape

    def set_activation_function(self, activation_function: str) -> None:
        """
        Sets the activation function for both the generator and discriminator.

        Args:
            activation_function (str): New activation function.

        Raises:
            ValueError: If activation_function is not a string.
        """
        if not isinstance(activation_function, str):
            raise ValueError("activation_function must be a string.")

        self._generator_builder._generator_activation_function = activation_function
        self._discriminator_builder._discriminator_activation_function = activation_function

    def set_last_layer_activation(self, last_layer_activation: str) -> None:
        """
        Sets the last layer activation function for both the generator and discriminator.

        Args:
            last_layer_activation (str): New activation function for the last layer.

        Raises:
            ValueError: If last_layer_activation is not a string.
        """
        if not isinstance(last_layer_activation, str):
            raise ValueError("last_layer_activation must be a string.")

        self._generator_builder._generator_last_layer_activation = last_layer_activation
        self._discriminator_builder._discriminator_last_layer_activation = last_layer_activation

    def set_dataset_type(self, dataset_type: torch.dtype) -> None:
        """
        Sets the dataset type for both the generator and discriminator.

        Args:
            dataset_type (torch.dtype): New dataset type.
        """
        self._generator_builder._generator_dataset_type = dataset_type
        self._discriminator_builder._discriminator_dataset_type = dataset_type

    def set_initializer_mean(self, initializer_mean: float) -> None:
        """
        Sets the initializer mean for both the generator and discriminator.

        Args:
            initializer_mean (float): New mean for parameter initialization.

        Raises:
            ValueError: If initializer_mean is not a number.
        """
        if not isinstance(initializer_mean, (float, int)):
            raise ValueError("initializer_mean must be a float or integer.")

        self._generator_builder._generator_initializer_mean = initializer_mean
        self._discriminator_builder._discriminator_initializer_mean = initializer_mean

    def set_initializer_deviation(self, initializer_deviation: float) -> None:
        """
        Sets the initializer deviation for both the generator and discriminator.

        Args:
            initializer_deviation (float): New deviation for parameter initialization.

        Raises:
            ValueError: If initializer_deviation is not a positive number.
        """
        if not isinstance(initializer_deviation, (float, int)) or initializer_deviation <= 0:
            raise ValueError("initializer_deviation must be a positive float or integer.")

        self._generator_builder._generator_initializer_deviation = initializer_deviation
        self._discriminator_builder._discriminator_initializer_deviation = initializer_deviation

    def set_dropout_decay_rate_generator(self, dropout_decay_rate_generator: float) -> None:
        """
        Sets the dropout decay rate for the generator.

        Args:
            dropout_decay_rate_generator (float): New dropout rate for generator.

        Raises:
            ValueError: If dropout rate is not between 0.0 and 1.0.
        """
        self._generator_builder.set_dropout_decay_rate_generator(dropout_decay_rate_generator)

    def set_dropout_decay_rate_discriminator(self, dropout_decay_rate_discriminator: float) -> None:
        """
        Sets the dropout decay rate for the discriminator.

        Args:
            dropout_decay_rate_discriminator (float): New dropout rate for discriminator.

        Raises:
            ValueError: If dropout rate is not between 0.0 and 1.0.
        """
        self._discriminator_builder.set_dropout_decay_rate_discriminator(dropout_decay_rate_discriminator)

    def set_dense_layer_sizes_generator(self, dense_layer_sizes_generator: List[int]) -> None:
        """
        Sets the dense layer sizes for the generator.

        Args:
            dense_layer_sizes_generator (List[int]): New layer sizes for generator.
        """
        self._generator_builder.set_dense_layer_sizes_generator(dense_layer_sizes_generator)

    def set_dense_layer_sizes_discriminator(self, dense_layer_sizes_discriminator: List[int]) -> None:
        """
        Sets the dense layer sizes for the discriminator.

        Args:
            dense_layer_sizes_discriminator (List[int]): New layer sizes for discriminator.
        """
        self._discriminator_builder.set_dense_layer_sizes_discriminator(dense_layer_sizes_discriminator)

    def get_generator_parameters(self) -> dict:
        """
        Returns the current configuration of the generator.

        Returns:
            dict: Dictionary containing generator configuration parameters.
        """
        return {
            'latent_dimension': self._generator_builder._generator_latent_dimension,
            'output_shape': self._generator_builder._generator_output_shape,
            'activation_function': self._generator_builder._generator_activation_function,
            'last_layer_activation': self._generator_builder._generator_last_layer_activation,
            'dropout_decay_rate': self._generator_builder._generator_dropout_decay_rate_g,
            'dense_layer_sizes': self._generator_builder._generator_dense_layer_sizes_g,
            'initializer_mean': self._generator_builder._generator_initializer_mean,
            'initializer_deviation': self._generator_builder._generator_initializer_deviation
        }

    def get_discriminator_parameters(self) -> dict:
        """
        Returns the current configuration of the discriminator.

        Returns:
            dict: Dictionary containing discriminator configuration parameters.
        """
        return {
            'latent_dimension': self._discriminator_builder._discriminator_latent_dimension,
            'output_shape': self._discriminator_builder._discriminator_output_shape,
            'activation_function': self._discriminator_builder._discriminator_activation_function,
            'last_layer_activation': self._discriminator_builder._discriminator_last_layer_activation,
            'dropout_decay_rate': self._discriminator_builder._discriminator_dropout_decay_rate_d,
            'dense_layer_sizes': self._discriminator_builder._discriminator_dense_layer_sizes_d,
            'initializer_mean': self._discriminator_builder._discriminator_initializer_mean,
            'initializer_deviation': self._discriminator_builder._discriminator_initializer_deviation
        }

    def to(self, device: torch.device):
        """
        Move both generator and discriminator models to the specified device.

        Args:
            device (torch.device): Target device (e.g., 'cuda' or 'cpu').

        Returns:
            self: Returns self for method chaining.
        """
        if self._generator_builder._generator_model_dense is not None:
            self._generator_builder._generator_model_dense.to(device)
        if self._discriminator_builder._discriminator_model_dense is not None:
            self._discriminator_builder._discriminator_model_dense.to(device)
        return self